[build]
  command = "yarn install --frozen-lockfile && yarn build"
  publish = "dist"
  node_version = "22"

[build.environment]
  NODE_VERSION = "22"
  NODE_ENV = "production"

# Handle Astro's static file serving
[[redirects]]
  from = "/assets/*"
  to = "/assets/:splat"
  status = 200

# Handle client-side routing
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Cache control for Astro's static assets
[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# Cache control for public directory assets
[[headers]] 
  for = "/public/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# Cache control for images
[[headers]]
  for = "/images/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# Cache control for fonts
[[headers]]
  for = "/fonts/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# Security headers
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Content-Security-Policy = "default-src 'self'; script-src 'self' 'unsafe-inline' 'unsafe-eval'; style-src 'self' 'unsafe-inline'; img-src 'self' data: https:; font-src 'self' data:; connect-src 'self'" 